### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by StevenRafft**
Adding important and crucial information

### CODE REVIEW

**Comment by StevenRafft** [comment]
It's true and crucial, It'd be a bad thing if someone didn't know it.

**Comment by jackssrt** [comment]
My GitHub profile is supposed to be professional.

**Comment by StevenRafft** [comment]
this is very professional trust me

**Comment by StevenRafft** [comment]
wait fuck they are coming i have to go

**Comment by StevenRafft** [comment]
192.168.1.1

**Pull request closed without merging**
